-- Resets the Snowflake demo source to a known state (20 rows). Safe to re-run.
CREATE DATABASE IF NOT EXISTS SIMPLE_REVERSE_ETL_DEMO;
CREATE SCHEMA IF NOT EXISTS SIMPLE_REVERSE_ETL_DEMO.DENTAL;

CREATE OR REPLACE TABLE SIMPLE_REVERSE_ETL_DEMO.DENTAL.DENTAL_CLAIMS (
    CLAIM_ID     NUMBER        NOT NULL,
    MEMBER_ID    NUMBER,
    CLAIM_STATUS VARCHAR(20),
    AMOUNT       NUMBER(10,2),
    UPDATED_AT   TIMESTAMP_NTZ
);

INSERT INTO SIMPLE_REVERSE_ETL_DEMO.DENTAL.DENTAL_CLAIMS
    (CLAIM_ID, MEMBER_ID, CLAIM_STATUS, AMOUNT, UPDATED_AT)
SELECT
    SEQ4() + 1                                                            AS CLAIM_ID,
    UNIFORM(10000, 99999, RANDOM())                                       AS MEMBER_ID,
    DECODE(MOD(SEQ4(), 3), 0,'SUBMITTED', 1,'PAID', 'DENIED')             AS CLAIM_STATUS,
    ROUND(UNIFORM(50, 5000, RANDOM()), 2)                                 AS AMOUNT,
    DATEADD('minute', -1 * UNIFORM(0, 20000, RANDOM()), CURRENT_TIMESTAMP()) AS UPDATED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 20));
